# Generated by Django 3.0.7 on 2020-07-25 14:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Product Attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Product Category')),
                ('isVisible', models.CharField(choices=[('show', 'show'), ('hide', 'hide')], default='show', max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=20, unique=True, verbose_name='Property')),
                ('value', models.CharField(max_length=500, verbose_name='Value')),
                ('property_description', models.CharField(default='', max_length=250, verbose_name='Property Description')),
                ('format', models.CharField(default='', max_length=50, verbose_name='Value Format')),
            ],
            options={
                'verbose_name_plural': 'Configurations',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('number', models.CharField(max_length=20, verbose_name='Contact Phone')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Order Date')),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='OrderTaker.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200, verbose_name='Product')),
                ('isVisible', models.CharField(choices=[('show', 'show'), ('hide', 'hide')], default='show', max_length=256)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='OrderTaker.Attribute')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='OrderTaker.Category')),
            ],
            options={
                'unique_together': {('category', 'product', 'attribute')},
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Item Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderTaker.Order')),
                ('product_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productattributes', to='OrderTaker.ProductAttribute')),
            ],
            options={
                'verbose_name_plural': 'Order Details',
            },
        ),
    ]
