# Generated by Django 3.0.7 on 2020-06-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderTaker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_id',
        ),
    ]
