# Generated by Django 3.0.7 on 2020-06-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderTaker', '0003_auto_20200614_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='id',
            new_name='item_ID',
        ),
    ]
