# Generated by Django 3.0.8 on 2020-07-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderTaker', '0004_auto_20200703_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='isVisible',
            field=models.CharField(choices=[('show', 'show'), ('hide', 'hide')], default='show', max_length=256),
        ),
    ]
