# Generated by Django 3.0.7 on 2020-06-15 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderTaker', '0004_auto_20200614_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_ID',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_Name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_Type',
            new_name='item_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_Quantity',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderTaker.Item')),
            ],
        ),
    ]
