# Generated by Django 3.0.8 on 2020-07-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderTaker', '0005_category_isvisible'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='isVisible',
            field=models.CharField(choices=[('show', 'show'), ('hide', 'hide')], default='show', max_length=256),
        ),
    ]
